### ISSUE TITLE
Interactive policy refresh – convenience optima via UX + design + parametrization (i.e. no R&D)

### ISSUE THREAD

**Issue by arjunhassard** [threshold-network/threshold#4]
In lieu of a successful R&D effort solving baton-passing (see #2 & #3), or during the potentially lengthy delay before it is operationalized, there must be a minimally inconvenient way for end-users (Alices) to reassign their policy to a new set of service-providers. 

The following primarily applies to the PRE application in its current form, but may be relevant to other Threshold apps. It also has a few network-wide implications – e.g. the universality of the minimum unbonding delay. 

In the scenario where some unacceptable % of the `n` Urusulas managing a sharing policy have submitted an unbonding transaction, it is inexpensive and uncomplicated for Alice to revoke an existing policy and then execute the grant function with the same label/underlying data. This _policy refresh_ generates a new group of Ursulas, all of whom are staked and have not initiated unbonding. 

How do we make this practical in the context of certain use cases? 

*Dead-man Switch & Transfer use case*
- Periodic interactively is baked into this use case – Alice must sign a transaction at a cadence equivalent to, in the case of non-signing, the acceptable _delay_ before the transfer occurs. For example, if asset-accessing credentials are to be transferred posthumously, this may be constrained by some local estate regulations. For the sake of argument, let's make this parameter 6 months. Note that regular manual signing is pretty much unavoidable, and can be likened to the annual requirement to choose+sign insurance plans via an employee dashboard (e.g. Gusto).
- Alice must sign a transaction at least every 6 months (the _delay tx_), which provides an opportunity to additionally complete a policy refresh, if necessary, with very low incremental inconvenience/cognitive load. 
- When is a refresh necessary? Weighing up transfer failure vs. cost/effort of refresh is subjective and therefore Alice could be presented with risk optionality here. Regardless, the dapp/UX will have to establish norms. For example, the policy refresh function is atomized in the _delay tx_ if:
(a) the % of Ursulas servicing the policy drops below 80%
or 
(b) `n` - `m` < 10
(Note that `m` does not automatically decrease when `n` decreases.)

*Private NFT Marketplace use case* [WIP]

*Generic use case*
- In many use cases, interactive policy refresh cannot be timed with some predictable participation from Alice. The goal is therefore to minimize inconvenience via parametrization, design tweaks and new UX. 
- A reliable notification system would provide Alice that assurance that any signs of Ursula group depletion are acted upon before they become a problem. This requires the list of Ursulas (on the TreasureMap and shared with Alice) and some kind of daemon monitoring each Ursula's staking status (on-chain events). This state could exist on a secure remote server (run by NuCypher initially), to facilitate the delivery of notifications to Alice in the instance that a threshold has been crossed – like (a) or (b) above – and a refresh is recommended/required. This slightly increases the attack and trust surface because Alice is trusting the server custodians (i.e. NuCypher Co) not to leak the list associated with a policy, but in practice this is not particularly sensitive information. There could also be an option to refresh the policy and not upload the new list of Ursulas to the server in the scenario that an Alice suspects any foul play or collusion underway. Furthermore, high `n` policies (see below) will involve a large % of all stakers anyway, so there is not much information to be gained by accessing this list. 
- High `n` policies reduce the probability of a critical mass of Ursulas unbonding in a given timestep and therefore reduce the frequency of necessary policy refreshes. 
- Increasing the unbonding delay for all PRE nodes (e.g. to 6 months) also reduces the frequency of necessary policy refreshes. This requires per-app unbonding rules in Threshold. 

All of the ideas mentioned in the *Generic use case* are also applicable to the *Dead-man Switch & Transfer use case*

**Comment by jMyles** [comment]
Any thoughts, @beaushinkle ?

**Comment by beaushinkle** [comment]
> In the scenario where some unacceptable % of the n Urusulas managing a sharing policy have submitted an unbonding transaction, it is inexpensive and uncomplicated for Alice to revoke an existing policy and then execute the grant function with the same label/underlying data. This policy refresh generates a new group of Ursulas, all of whom are staked and have not initiated unbonding.

With you so far: we have a similar concept in tbtc v2. Once a wallet is at risk of becoming unable to transfer funds, we make it transfer whatever it still has while it still can. Here, alice revokes one set of dying ursulas, and then immediately gives permissions to the same folks as before using a fresh set of ursulas.

The side effects are:

+ temporary outage
+ some ursulas have more/less policies to watch over
+ gas
+ alice's policy has 100% bonded ursulas

> Dead-man Switch & Transfer use case

Ahhhh, since you have to manually do something every X amount of time or the policy drops, then if something relies on the policy and I stop refreshing it (for whatever reason, like :skull:) then that downstream thing also stops. Just like those boat keys you attach to your lifejacket where if you fall out of the boat it rips the key out of the ignition and the boat stops! :100:

> When is a refresh necessary? Weighing up transfer failure vs. cost/effort of refresh is subjective and therefore Alice could be presented with risk optionality here. Regardless, the dapp/UX will have to establish norms. For example, the policy refresh function is atomized in the delay tx if:
(a) the % of Ursulas servicing the policy drops below 80%
or
(b) n - m < 10
(Note that m does not automatically decrease when n decreases.)

I know that `n` is the number of ursulas servicing alice's policy. What is `m`? So far, I've been kicking the can for these sorts of decisions down the road and making all of these params (the percentage of ursulas before we get scared and refresh, how many ursulas for a policy, etc) governable params in tbtcv2 land. How much do you think folks will want to customize those params? Would it be worth the complexity (both in solidity and in UX) of having governable *defaults* and then letting people pay to override on a per-policy basis?

> A reliable notification system would provide Alice that assurance that any signs of Ursula group depletion are acted upon before they become a problem. This requires the list of Ursulas (on the TreasureMap and shared with Alice) and some kind of daemon monitoring each Ursula's staking status (on-chain events). This state could exist on a secure remote server (run by NuCypher initially), to facilitate the delivery of notifications to Alice in the instance that a threshold has been crossed – like (a) or (b) above – and a refresh is recommended/required. This slightly increases the attack and trust surface because Alice is trusting the server custodians (i.e. NuCypher Co) not to leak the list associated with a policy, but in practice this is not particularly sensitive information. 

Another option here is to write an open-source self-hostable monitoring implementation. Folks can either trust someone who runs one or run their own, similar to https://github.com/boar-network/keep-monitoring
